### PR TITLE
DynamicStack

### PR DESCRIPTION
**Pull request by renehiemstra**
* concepts for Stack and Dstack
* DynamicStack implementation
* __cast from DynamicStack to DynamicVector, works only on rvalues and moves resources over.

### CODE REVIEW

**Comment by tpkessler** [comment]
Tests fail for me:
```
./stack.t:149: user-defined cast failed: ./smartmem.t:147: Arguments to cast need to be of generic type SmartBlock.
stack traceback:
	[C]: in function 'error'
	./smartmem.t:147: in function <./smartmem.t:136>
	[C]: in function 'xpcall'
	./stack.t:149: Errors reported during invoking __cast
        to.data = from.data:__move()
```

**Comment by renehiemstra** [comment]
There should not be a cast happening here. Maybe you can investigate what happened?

**Comment by renehiemstra** [comment]
Are you using the latest terra? branch raii-v2?

**Comment by tpkessler** [comment]
Caused by outdated terra. Fixed now!

**Pull request merged**
